name: cartanawc_app
description: Cartana Woocommerce application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.41.2
  cupertino_icons: ^1.0.2
  dartz:
  data_connection_checker: ^0.3.4
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_html: ^0.11.1
  flutter_svg: ^0.19.0
  freezed: ^0.12.7
  geolocator: ^6.2.1
  get_it: ^5.0.6
  get_version: ^0.2.2
  google_maps_flutter: ^1.2.0
  json_serializable: ^3.5.1
  overlay_support: ^1.0.5
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  rxdart: ^0.25.0
  shared_preferences: ^2.0.6

dev_dependencies:
  build_runner: ^1.10.0
  flutter_native_splash: ^0.3.2
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/images/cartana_logo.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
