name: cartanawc_app
description: Cartana Woocommerce application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+12

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  # Badges updated -> 20/08/2022
  badges: ^2.0.3
  # Cupertino_icons updated -> 20/08/2022
  cupertino_icons: ^1.0.5
  # Dartz updated -> 30/04/2022
  dartz: ^0.10.1
  # Data Connection Checker updated -> 30/04/2022
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  # Dio updated -> 30/04/2022
  dio: ^4.0.6
  flutter:
    sdk: flutter
  # Flutter_dotenv updated -> 30/04/2022
  flutter_dotenv: ^5.0.2
  # Flutter_html updated -> 30/04/2022
  flutter_html: ^2.2.1
  # Flutter_svg updated -> 20/08/2022 ->
  flutter_svg: ^0.23.0+1
  # Geolocator updated 30/04/2022
  # geolocator: ^8.0.5
  geolocator: ^7.5.0
  # Get_it updated-> 30/04/2022
  get_it: ^7.2.0
  # Google_maps_flutter updates -> 24/11/2022 ->
  google_maps_flutter: ^2.1.12
  # Intl -> 16/11/2022
  intl: ^0.17.0
  # Provider updated -> 24/11/2022
  provider: ^6.0.4
  # Rxdart updated -> 24/11/2022
  rxdart: ^0.27.7
  ## Shared_preferences updated -> 23/11/2022 ->
  shared_preferences: ^2.0.15

dev_dependencies:
  # Aanalyzer updated -> 23/11/2022
  analyzer: ^4.1.0
  ##build_runner: ^1.10.0
  build_runner: ^2.0.0
  ## Flutter_native_splash updated -> 23/11/2022 ->
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  # Freezed updated -> 23/11/2022
  freezed: ^2.0.4
  #Json_serializable updated -> 24/11/2022
  json_serializable: ^6.3.1
  ## Lint updated -> 23/11/2022
  lint: ^1.8.2

  pretty_dio_logger: ^1.1.1

flutter_native_splash:
  color: "#000000"
  image: assets/images/cartana_logo.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
